version: '2'

services:
    ingress:
        image: traefik:1.3-alpine
        command: --web --docker
        ports:
            - "80:80"
            - "8080:8080"
            - "1080:1080"
            - "4444:4444"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        labels:
            - "traefik.enable=false"
    db:
        image: mysql
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        labels:
            - "traefik.enable=false"
    php:
        build: php7-fpm
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/logs
        links:
            - "db"
            - "mailcatcher"
        labels:
            - "traefik.enable=false"
    nginx:
        build: nginx
        links:
            - "php"
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
        networks:
            - traefik
            - default
        labels:
            - "traefik.backend=nginx"
            - "traefik.frontend.rule=Host:uqam.app"
            - "traefik.docker.network=traefik"
            - "traefik.port=80"
    phantomjs:
        image: shufo/phantomjs
        extra_hosts:
            - ${DOMAIN}:172.25.0.4
        command: --webdriver 4444
        networks:
            - traefik
            - default
        labels:
            - "traefik.backend=phantomjs"
            - "traefik.frontend.rule=Host:phantomjs.localhost"
            - "traefik.docker.network=traefik"
            - "traefik.port=4444"
    mailcatcher:
        image: yappabe/mailcatcher
        #image: schickling/mailcatcher
        environment:
            MAILCATCHER_PORT: 1025
        labels:
            - "traefik.backend=mailcatcher"
            - "traefik.frontend.rule=Host:mailcatcher.localhost"
            - "traefik.docker.network=traefik"
            - "traefik.port=1080"
    #blackfire:
    #   image: blackfire/blackfire
    #   environment:
    #        - BLACKFIRE_SERVER_ID=${BLACKFIRE_SERVER_ID}
    #        - BLACKFIRE_SERVER_TOKEN=${BLACKFIRE_SERVER_TOKEN}
    #   networks:
    #       mynet:
    #           ipv4_address: 172.25.0.7
networks:
    traefik: ~
    default: ~