AppBundle\Entity\Workcpace:
    type: entity
    table: workcpace
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        description:
            type: text
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
