AppBundle\Entity\User:
    user{1..10}:
        username: <userName()>
        email: <email()>
        password: <password()>
AppBundle\Entity\Workcpace:
    workcpace{1..3}:
        name: <word()>
        description: <text()>
AppBundle\Entity\Project:
    project{1..7}:
        title: <word()>
        description: <text()>
        dueDate: <dateTimeBetween('now', '+9 days')>
        workcpace: "@workcpace*"
AppBundle\Entity\Task:
    task{1..15}:
        title: <word()>
        description: <text()>
        dueDate: <dateTimeBetween('now', '+3 months')>
        attachment: <boolean(50)>
        project: "@project*"
        user: "@user*"